server:
  port: 9095
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
springdoc:
  api-docs:
    path: /userswagger-openapi
        